name: rpa_bot_monitoring_ui
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  app_settings: ^5.1.1
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  logging: ^1.3.0
  pinput: ^5.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:
  assets:
    - assets/images/my_picture.png
    - assets/images/onboarding.png
  uses-material-design: true

  