import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});
  final Color customTeal = const Color.fromARGB(255, 66, 105, 105);
  final String privacyPolicyText = """

Our Privacy Policy was last updated on June 13, 2024.

This Privacy Policy outlines the policies and procedures for the collection, use, and disclosure of your
information when you use the RPA Bot Monitor mobile app ("the App"). It also informs you about your privacy rights
and how the law protects your data. By using the App, you agree to the collection and use of information in
accordance with this Privacy Policy.
Interpretation and Definitions

Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions.
The following definitions shall have the same meaning regardless of whether they appear in singular or in
plural.

Definitions

For the purposes of this Privacy Policy:


● "Account" means a unique account created for you to access our Service or parts of our Service.


● "Business", for the purpose of the CCPA (California Consumer Privacy Act), refers to the Company
as the legal entity that collects Consumers' personal information and determines the purposes and
means of the processing of Consumers' personal information, or on behalf of which such
information is collected and that alone, or jointly with others, determines the purposes and means of
the processing of consumers' personal information, that does business in the State of California.


● "Company" (referred to as either "the Company", "We", "us" or "Our" in this Agreement) refers to H-
Vault.

For the purpose of the GDPR, the Company is the Data Controller.


● "Country" refers to INDIA.


● "Consumer", for the purpose of the CCPA (California Consumer Privacy Act), means a natural
person who is a California resident. A resident, as defined in the law, includes (1) every individual
who is in the USA for other than a temporary or transitory purpose, and (2) every individual who is
domiciled in the USA who is outside the USA for a temporary or transitory purpose.


● "Cookies" are small files that are placed on your computer, mobile device or any other device by a
website, containing the details of your browsing history on that website among its many uses.


● "Data Controller", for the purposes of the GDPR (General Data Protection Regulation), refers to the

Company as the legal person which alone or jointly with others determines the purposes and means
of the processing of Personal Data.


● "Device" means any device that can access the Service such as a computer, a cell phone or a
digital tablet.


● "Do Not Track" (DNT)” is a concept that has been promoted by US regulatory authorities, in
particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and
implement a mechanism for allowing internet users to control the tracking of their online activities
across websites.


● "Personal Data" is any information that relates to an identified or identifiable individual.

For the purposes of GDPR, Personal Data means any information relating to you such as a name,
an identification number, location data, online identifier or to one or more factors specific to the
physical, physiological, genetic, mental, economic, cultural or social identity.

For the purposes of the CCPA, Personal Data means any information that identifies, relates to,
describes or is capable of being associated with, or could reasonably be linked, directly or indirectly,
with you.


● "Sale", for the purpose of the CCPA (California Consumer Privacy Act), means selling, renting,
releasing, disclosing, disseminating, making available, transferring, or otherwise communicating
orally, in writing, or by electronic or other means, a Consumer's personal information to another
business or a third party for monetary or other valuable consideration.


● "Service" refers to the Application.


● "Service Provider" means any natural or legal person who processes the data on behalf of the
Company. It refers to third-party companies or individuals employed by the Company to facilitate the
Service, to provide the Service on behalf of the Company, to perform services related to the Service
or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR,
Service Providers are considered Data Processors.


● "Usage Data" refers to data collected automatically, either generated by the use of the Service or
from the Service infrastructure itself (for example, the duration of a page visit).


● "Application" refers to RPA Bot Monitor, accessible from Google Play Store.


● "You" means the individual accessing or using the Service, or the company, or other legal entity on
behalf of which such individual is accessing or using the Service, as applicable.

Under GDPR (General Data Protection Regulation), you can be referred to as the Data Subject or
as the User as you are the individual using the Service.


Collecting and Using your Personal Data

Types of Data Collected

Personal Data

While using RPA Bot Monitor, we may ask you to provide us with certain personally identifiable information that can
be used to contact or identify you. This information may include:


● Email address
● First name and last name
● Phone number
● Address, State, Province, ZIP/Postal code, City
● Usage Data

Usage Data

Usage Data is collected automatically when you use the app. This may include:


• your device's Internet Protocol address (e.g., IP address)
• Device type and version
• Pages visited within the app
• Time and date of app usage
• Time spent on app pages
• Unique device identifiers
• Other diagnostic data


When you access the app through a mobile device, we may collect additional information, including the
type of mobile device you use, your mobile device's unique ID, your mobile device's IP address, your
mobile operating system, and other diagnostic data.

We may also collect information you send whenever you use RPA Bot Monitor.
.


Use of your Personal Data

RPA Bot Monitor may use your personal data for the following purposes:


● Providing and Maintaining the Service: We use your personal data to provide and maintain our
mobile app. This includes monitoring the usage of our app.


 Managing your Account: your personal data is used to manage your registration as a user of the

app. The information you provide grants you access to various functionalities available to registered
users.


 Performance of a Contract: We process your personal data to develop, comply with, and execute

the contract for the products, items, or services you've purchased or any other contract with us
through the app.


 Contacting you: We may contact you through email, telephone calls, SMS, or other equivalent
electronic communication methods, including push notifications within the app. This contact may
involve updates, informative communications related to functionalities, products, or contracted
services, as well as security updates when necessary or reasonable for their implementation.


 Providing News, Special Offers, and General Information: We use your personal data to provide

you with news, special offers, and general information about other goods, services, and events that
are similar to those you've purchased or inquired about, unless you have opted out of receiving
such information.


 Managing your Requests: We use your data to attend to and manage your requests to us.


 Business Transfers: In the event of a merger, divestiture, restructuring, reorganization, dissolution,

or other sale or transfer of some or all of our assets, your personal data may be used as part of the
assets transferred. This may occur as a going concern or as part of bankruptcy, liquidation, or
similar proceedings.


 Other Purposes: your data may be used for other purposes, including data analysis, identifying

usage trends, evaluating the effectiveness of our promotional campaigns, and improving our app,
products, services, marketing, and your user experience.


We may share your personal information in the following situations:


● With Service Providers: We may share your personal information with service providers to monitor
and analyze the use of our app, for payment processing, and to contact you.

● For business transfers: your personal information may be shared or transferred in connection
with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or
a portion of our business by another company.

● With Affiliates: We may share your information with our affiliates, subject to their agreement to
adhere to this Privacy Policy. Affiliates include our parent company and any subsidiaries, joint
venture partners, or companies under common control with us.

● With business partners: We may share your information with our business partners to offer you
certain products, services, or promotions.

● With other users: When you share personal information or interact in public areas with other users
within the app, that information may be viewed by all users and may be publicly distributed outside
the app.

● With your consent: We may disclose your personal information for any other purpose with your
explicit consent.

Retention of your Personal Data

RPA Bot Monitor will retain your personal data only for as long as it is necessary for the purposes outlined in this
Privacy Policy. We will keep and use your personal data as required to comply with our legal obligations,
such as retaining your data to adhere to applicable laws, settle disputes, and enforce our legal agreements
and policies.

We will also retain usage data for internal analysis purposes. Usage data is typically retained for a shorter
duration, except when this data is used to enhance security or improve the functionality of our app, or when
we are legally obligated to retain this data for longer periods.

Transfer of your Personal Data

your information, including Personal Data, is processed at RPA Bot Monitor's operating offices and other locations
where the parties involved in data processing are situated. This means that your information may be
transferred to and stored on computers located outside your state, province, country, or other governmental
jurisdiction, where data protection laws may differ from those in your jurisdiction.

By consenting to this Privacy Policy and providing such information, you agree to the transfer of your data.
RPA Bot Monitor will take all reasonable steps to ensure that your data is handled securely and in accordance with
this Privacy Policy. We will not transfer your Personal Data to any organization or country without
implementing adequate controls to safeguard your data and other personal information.

Disclosure of your Personal Data

Business Transactions

In the event that RPA Bot Monitor is involved in a merger, acquisition, or asset sale, your Personal Data may be
transferred. We will provide you with notice before your Personal Data is transferred and becomes subject
to a different Privacy Policy.

Law enforcement

Under certain circumstances, RPA Bot Monitor may be required to disclose your Personal Data if mandated by law
or in response to valid requests from public authorities, such as a court or government agency.


Other legal requirements

RPA Bot Monitor may disclose your Personal Data in good faith when such action is deemed necessary to:


● Comply with a Legal Obligation.
 Protect and Defend the Rights or Property of RPA Bot Monitor.
 Prevent or Investigate Possible Wrongdoing in Connection with the Service.
 Protect the Personal Safety of Users of the Service or the Public.
 Protect Against Legal Liability.



Security of your Personal Data

The security of your Personal Data is a priority for us. It's important to note that while we make every effort
to use commercially acceptable methods to protect your Personal Data, no method of transmission over the
Internet or electronic storage can be guaranteed to be 100% secure.

We will continue to work diligently to safeguard your information, but we cannot ensure its absolute
security.

GDPR Privacy Policy

Legal Basis for Processing Personal Data under GDPR

We may process Personal Data under the following conditions:


● Consent: you have given your consent for processing Personal Data for one or more specific
purposes

● Performance of a contract: Provision of Personal Data is necessary for the performance of an
agreement with you and/or for any pre-contractual obligations thereof.

● Legal obligations: Processing Personal Data is necessary for compliance with a legal obligation to
which the Company is subject.

● Vital interests: Processing Personal Data is necessary in order to protect your vital interests or of
another natural person.

● Public interests: Processing Personal Data is related to a task that is carried out in the public
interest or in the exercise of official authority vested in the Company.

● Legitimate interests: Processing Personal Data is necessary for the purposes of the legitimate
interests pursued by the Company.


In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing,
and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a
requirement necessary to enter into a contract.

Your Rights under the GDPR

The Company undertakes to respect the confidentiality of your Personal Data and to guarantee you can
exercise your rights.

you have the right under this Privacy Policy, and by law if you are within the EU, to:


● Request access to your Personal Data. The right to access, update or delete the information We
have on you. Whenever made possible, you can access, update or request deletion of your
Personal Data directly within your account settings section. If you are unable to perform these
actions yourself, please contact us to assist you. This also enables you to receive a copy of the
Personal Data We hold about you.

● Request correction of the Personal Data that We hold about you. you have the right to have
any incomplete or inaccurate information We hold about you corrected.

● Object to processing of your Personal Data. This right exists where We are relying on a
legitimate interest as the legal basis for Our processing and there is something about your particular
situation, which makes you want to object to our processing of your Personal Data on this ground.
you also have the right to object where We are processing your Personal Data for direct marketing
purposes.

● Request erasure of your Personal Data. you have the right to ask us to delete or remove
Personal Data when there is no good reason for us to continue processing it.

● Request the transfer of your Personal Data. We will provide to you, or to a third-party you have
chosen, your Personal Data in a structured, commonly used, machine-readable format. Please note
that this right only applies to automated information which you initially provided consent for us to
use or where We used the information to perform a contract with you.

● Withdraw your consent. you have the right to withdraw your consent on using your Personal Data.
If you withdraw your consent, We may not be able to provide you with access to certain specific
functionalities of the Service.

● Actions Against Misuse or Illegal Activities.
We reserve the right to take appropriate actions against any requestor if we become aware of any illegal
activities or misuse of information provided through our platform. Our commitment to maintaining a
secure and trustworthy environment empowers us to investigate, report, and take necessary legal actions
to address any activities that contravene the law or our terms of service. This may include, but is not
limited to, suspending or terminating the user's access to our services and cooperating with law
enforcement authorities in accordance with applicable legal requirements. It is important to note that
hvault is not responsible if a donor decides to take any actions against you based on their discretion
and interpretation of the situation.

● Sharing of Location and Contact Information with Requestor.
By expressing interest in a blood donation request through our platform, you agree to our disclaimer
and consent to the sharing of your distance location and mobile phone number with the requestor.
This information is shared solely for the purpose of facilitating the connection between donors and
requestors, enhancing the efficiency of the donation process. We take your privacy seriously and
implement stringent security measures to protect your personal information. However, it is your
responsibility to ensure that you are comfortable with sharing this information under the terms outlined
in this policy.

Exercising of your GDPR Data Protection Rights

you may exercise your rights of access, rectification, cancellation and opposition by contacting us. Please
note that we may ask you to verify your identity before responding to such requests. If you make a request,
We will try our best to respond to you as soon as possible.

you have the right to complain to a Data Protection Authority about Our collection and use of your Personal
Data. For more information, if you are in the European Economic Area (EEA), please contact your local
data protection authority in the EEA.

CCPA Privacy Policy

This privacy notice section for California residents supplements the information contained in Our Privacy
Policy and it applies solely to all visitors, users, and others who reside in the State of California.

Categories of Personal Information Collected

We collect information that identifies, relates to, describes, references, is capable of being associated with,
or could reasonably be linked, directly or indirectly, with a particular Consumer or Device. The following is a
list of categories of personal information which we may collect or may have been collected from California
residents within the last twelve (12) months.

Please note that the categories and examples provided in the list below are those defined in the CCPA.
This does not mean that all examples of that category of personal information were in fact collected by us,
but reflects our good faith belief to the best of our knowledge that some of that information from the
applicable category may be and may have been collected. For example, certain categories of personal
information would only be collected if you provided such personal information directly to us.


● Category A: Identifiers.

Examples: A real name, alias, postal address, unique personal identifier, online identifier, Internet
Protocol address, email address, account name, driver's license number, passport number, or other
similar identifiers.

Collected: Yes.


● Category B: Personal information categories listed in the California Customer Records
statute (Cal. Civ. Code § 1798.80(e)).

Examples: A name, signature, Social Security number, physical characteristics or description,
address, telephone number, passport number, driver's license or state identification card number,
insurance policy number, education, employment, employment history, bank account number, credit
card number, debit card number, or any other financial information, medical information, or health
insurance information. Some personal information included in this category may overlap with other
categories.

Collected: Yes.


● Category C: Protected classification characteristics under California or federal law.

Examples: Age (40 years or older), race, color, ancestry, national origin, citizenship, religion or
creed, marital status, medical condition, physical or mental disability, sex (including gender, gender
identity, gender expression, pregnancy or childbirth and related medical conditions), sexual
orientation, veteran or military status, genetic information (including familial genetic information).

Collected: No.


● Category D: Commercial information.

Examples: Records and history of products or services purchased or considered.

Collected: Yes.


● Category E: Biometric information.

Examples: Genetic, physiological, behavioral, and biological characteristics, or activity patterns used
to extract a template or other identifier or identifying information, such as, fingerprints, faceprints,
and voiceprints, iris or retina scans, keystroke, gait, or other physical patterns, and sleep, health, or
exercise data.

Collected: No.


● Category F: Internet or other similar network activity.


Examples: Interaction with our Service or advertisement.

Collected: Yes.


● Category G: Geolocation data.

Examples: Approximate physical location.

Collected: Yes.


● Category H: Sensory data.

Examples: Audio, electronic, visual, thermal, olfactory, or similar information.

Collected: No.


● Category I: Professional or employment-related information.

Examples: Current or past job history or performance evaluations.

Collected: No.


● Category J: Non-public education information (per the Family Educational Rights and
Privacy Act (20 U.S.C. Section 1232g, 34 C.F.R. Part 99)).

Examples: Education records directly related to a student maintained by an educational institution or
party acting on its behalf, such as grades, transcripts, class lists, student schedules, student
identification codes, student financial information, or student disciplinary records.


Collected: No.


● Category K: Inferences drawn from other personal information.

Examples: Profile reflecting a person's preferences, characteristics, psychological trends,
predispositions, behavior, attitudes, intelligence, abilities, and aptitudes.

Collected: No.


Under CCPA, personal information does not include:


● Publicly available information from government records
● Deidentified or aggregated consumer information
● Information excluded from the CCPA's scope, such as:
● Health or medical information covered by the Health Insurance Portability and Accountability Act of

1996 (HIPAA) and the California Confidentiality of Medical Information Act (CMIA) or clinical trial
data

● Personal Information covered by certain sector-specific privacy laws, including the Fair Credit
Reporting Act (FRCA), the Gramm-Leach-Bliley Act (GLBA) or California Financial Information
Privacy Act (FIPA), and the Driver's Privacy Protection Act of 1994

Sources of Personal Information

We obtain the categories of personal information listed above from the following categories of sources:


● Directly from you. For example, from the forms you complete on our app, preferences you express
or provide through our Service, or from your purchases on our app.

● Indirectly from you. For example, from observing your activity on our app.
● Automatically from you. For example, through cookies we or our service providers set on your

device as you navigate through our app.
● From Service Providers. For example, third-party vendors to monitor and analyze the use of our

Service, third-party vendors for payment processing, or other third-party vendors that We use to
provide the Service to you.

Use of Personal Information for Business Purposes or Commercial Purposes

We may use or disclose personal information We collect for "business purposes" or "commercial purposes"
(as defined under the CCPA), which may include the following examples:


● To operate our Service and provide you with our Service.
● To provide you with support and to respond to your inquiries, including to investigate and address

your concerns and monitor and improve our Service.
● To fulfill or meet the reason you provided the information. For example, if you share your contact

information to ask a question about our Service, We will use that personal information to respond to
your inquiry. If you provide your personal information to purchase a product or service, We will use
that information to process your payment and facilitate delivery.

● To respond to law enforcement requests and as required by applicable law, court order, or
governmental regulations.

● As described to you when collecting your personal information or as otherwise set forth in the
CCPA.

● For internal administrative and auditing purposes.
● To detect security incidents and protect against malicious, deceptive, fraudulent or illegal activity,

including, when necessary, to prosecute those responsible for such activities.

Please note that the examples provided above are illustrative and not intended to be exhaustive. For more
details on how we use this information, please refer to the "Use of your Personal Data" section.

If We decide to collect additional categories of personal information or use the personal information We
collected for materially different, unrelated, or incompatible purposes We will update this Privacy Policy.

Disclosure of Personal Information for Business Purposes or Commercial Purposes

We may use or disclose and may have used or disclosed in the last twelve (12) months the following
categories of personal information for business or commercial purposes:


● Category A: Identifiers
● Category B: Personal information categories listed in the California Customer Records statute (Cal.

Civ. Code § 1798.80(e))
● Category D: Commercial information
● Category F: Internet or other similar network activity


Please note that the categories listed above are those defined in the CCPA. This does not mean that all
examples of that category of personal information were in fact disclosed, but reflects our good faith belief to
the best of our knowledge that some of that information from the applicable category may be and may have
been disclosed.

When We disclose personal information for a business purpose or a commercial purpose, We enter a
contract that describes the purpose and requires the recipient to both keep that personal information
confidential and not use it for any purpose except performing the contract.

As defined in the California Consumer Privacy Act (CCPA), "sell" and "sale" encompass various activities,
including selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise
communicating personal information to a third party for valuable consideration. This valuable consideration
may not always be monetary but can take various forms.

Please note that the categories listed below align with those defined in the CCPA. This does not imply that
all examples of personal information within each category were sold, but rather reflects our good faith
belief, to the best of our knowledge, that some information from these categories may have been shared in
exchange for value.

We may have sold and may sell in the last twelve (12) months the following categories of personal
information:


 Category A: Identifiers
 Category B: Personal information categories listed in the California Customer Records statute (Cal.

Civ. Code § 1798.80(e))
 Category D: Commercial information
 Category F: Internet or other similar network activity

Share of Personal Information

We may share your personal information identified in the above categories with the following categories of
third parties:


● Service Providers
● Payment processors
● Our affiliates
● Our business partners
● Third party vendors to whom you or your agents authorize us to disclose your personal information

in connection with products or services We provide to you

Sale of Personal Information of Minors Under 16 Years of Age

We do not knowingly collect personal information from minors under the age of 16 through our Service,
although certain third-party websites that we link to may do so. These third-party websites have their own
terms of use and privacy policies, and we encourage parents and legal guardians to monitor their children's
Internet usage and instruct their children to never provide information on other websites without their
permission.

We do not sell the personal information of consumers we actually know are less than 16 years of age
unless we receive affirmative authorization (the "right to opt-in") from either the consumer who is between
13 and 16 years of age or the parent or guardian of a consumer less than 13 years of age. Consumers who
opt-in to the sale of personal information may opt-out of future sales at any time. To exercise the right to
opt-out, you (or your authorized representative) may submit a request to us by contacting us.

If you have reason to believe that a child under the age of 13 (or 16) has provided us with personal
information, please contact us with sufficient detail to enable us to delete that information.

Your Rights under the CCPA

The CCPA provides California residents with specific rights regarding their personal information. If you are
a resident of California, you have the following rights:


● The right to notice. you have the right to be notified which categories of Personal Data are being
collected and the purposes for which the Personal Data is being used.

● The right to request. Under CCPA, you have the right to request that We disclose information to
you about Our collection, use, sale, disclosure for business purposes and share of personal
information. Once We receive and confirm your request, We will disclose to you:

○ The categories of personal information We collected about you
○ The categories of sources for the personal information We collected about you
○ Our business or commercial purpose for collecting or selling that personal information
○ The categories of third parties with whom We share that personal information
○ The specific pieces of personal information We collected about you
○ If we sold your personal information or disclosed your personal information for a business

purpose, We will disclose to you:
■ The categories of personal information categories sold
■ The categories of personal information categories disclosed

● The right to say no to the sale of Personal Data (opt-out). you have the right to direct us to not
sell your personal information. To submit an opt-out request please contact us.

● The right to delete Personal Data. you have the right to request the deletion of your Personal
Data, subject to certain exceptions. Once We receive and confirm your request, We will delete (and
direct Our Service Providers to delete) your personal information from our records, unless an

exception applies. We may deny your deletion request if retaining the information is necessary for
us or Our Service Providers to:

○ Complete the transaction for which We collected the personal information, provide a good or
service that you requested, take actions reasonably anticipated within the context of our
ongoing business relationship with you, or otherwise perform our contract with you.

○ Detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity,
or prosecute those responsible for such activities.

○ Debug products to identify and repair errors that impair existing intended functionality.
○ Exercise free speech, ensure the right of another consumer to exercise their free speech

rights, or exercise another right provided for by law.
○ Comply with the California Electronic Communications Privacy Act (Cal. Penal Code § 1546

et. seq.).
○ Engage in public or peer-reviewed scientific, historical, or statistical research in the public

interest that adheres to all other applicable ethics and privacy laws, when the information's
deletion may likely render impossible or seriously impair the research's achievement, if you
previously provided informed consent.

○ Enable solely internal uses that are reasonably aligned with consumer expectations based
on your relationship with us.

○ Comply with a legal obligation.
○ Make other internal and lawful uses of that information that are compatible with the context

in which you provided it.
● The right not to be discriminated against. you have the right not to be discriminated against for

exercising any of your consumer's rights, including by:
○ Denying goods or services to you
○ Charging different prices or rates for goods or services, including the use of discounts or

other benefits or imposing penalties
○ Providing a different level or quality of goods or services to you
○ Suggesting that you will receive a different price or rate for goods or services or a different

level or quality of goods or services

Exercising your CCPA Data Protection Rights

In order to exercise any of your rights under the CCPA, and if you are a California resident, you can contact
us:


● By visiting this page on our website: https://rpabotmonitor.com
● By sending us an email: appsupport@rpabotmonitor.com


Only you, or a person registered with the California Secretary of State that you authorize to act on your
behalf, may make a verifiable request related to your personal information.

your request to us must:


● Provide sufficient information that allows us to reasonably verify you are the person about whom We
collected personal information or an authorized representative

● Describe your request with sufficient detail that allows us to properly understand, evaluate, and
respond to it


We cannot respond to your request or provide you with the required information if we cannot:


● Verify your identity or authority to make the request
● And confirm that the personal information relates to you

● We will disclose and deliver the required information free of charge within 45 days of receiving your
verifiable request. The time period to provide the required information may be extended once by an
additional 45 days when reasonably necessary and with prior notice.


Any disclosures We provide will only cover the 12-month period preceding the verifiable request's receipt.

For data portability requests, We will select a format to provide your personal information that is readily
usable and should allow you to transmit the information from one entity to another entity without hindrance.


Do Not Sell My Personal Information

You have the right to opt-out of the sale of your personal information. Once we receive and confirm a
verifiable consumer request from you, we will stop selling your personal information. To exercise your right
to opt-out, please contact us.

The service providers we partner with (for example, our analytics or advertising partners) may use
technology on the App that may be considered as selling personal information under CCPA law. If you wish
to opt out of the use of your personal information for interest-based advertising purposes and these
potential sales as defined under CCPA law, you may do so by following the instructions below.

Please note that any opt-out is specific to the device and browser you use, and you may need to opt out on
each device and browser you use.


Website

You can opt out of receiving personalized ads served by our Service Providers by following the instructions
presented on the App:


● The NAI's opt-out platform: http://www.networkadvertising.org/choices/
● The EDAA's opt-out platform http://www.youronlinechoices.com/
● The DAA's opt-out platform: http://optout.aboutads.info/?c=2&lang=EN


The opt out will place a cookie on your computer that is unique to the browser you use to opt out. If you
change browsers or delete the cookies saved by your browser, you will need to opt out again.

Mobile Devices

Your mobile device may give you the ability to opt out of the use of information about the apps you use to
serve you ads targeted to your interests:

 On Android devices, you can select "Opt out of Interest-Based Ads" or "Opt out of Ads
Personalization."

 On iOS devices, you can enable "Limit Ad Tracking."

You can also stop the collection of location information from your mobile device by changing the
preferences on your mobile device.

"Do Not Track" Policy as Required by California Online Privacy Protection
Act (CalOPPA)

Our App does not respond to Do Not Track signals.

However, please note that some third-party websites may track your browsing activities. If you visit such
websites, you can set your preferences in your web browser to inform websites that you do not want to be
tracked. You can enable or disable "Do Not Track" (DNT) by visiting the preferences or settings page of
your web browser.

Children's Privacy

Our App does not address anyone under the age of 13. We do not knowingly collect personally identifiable
information from anyone under the age of 13. If you are a parent or guardian and you are aware that your
child has provided us with Personal Data, please contact us. If We become aware that We have collected
Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to
remove that information from Our servers.

If We need to rely on consent as a legal basis for processing your information and your country requires
consent from a parent, We may require your parent's consent before We collect and use that information.

Your California Privacy Rights (California's Shine the Light law)

Under California Civil Code Section 1798 (California's Shine the Light law), California residents with an
established business relationship with us can request information once a year about sharing their Personal
Data with third parties for the third parties' direct marketing purposes.

If you'd like to request more information under the California Shine the Light law, and if you are a California
resident, you can contact us using the contact information provided below.

California Privacy Rights for Minor Users (California Business and
Professions Code Section 22581)

California Business and Professions Code Section 22581 allows California residents under the age of 18
who are registered users of online sites, services or applications to request and obtain removal of content
or information they have publicly posted.

To request removal of such data, and if you are a California resident, you can contact us using the contact
information provided below, and include the email address associated with your account.

Be aware that your request does not guarantee complete or comprehensive removal of content or
information posted online and that the law may not permit or require removal in certain circumstances.

Links to Other Websites

Our Service may contain links to other websites that are not operated by us. If you click on a third party link,
you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every
site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any
third party sites or services.

Changes to this Privacy Policy

We may update Our Privacy Policy from time to time. We will notify you of any changes by posting the new
Privacy Policy on this page.

We will let you know via email and/or a prominent notice on Our Service, prior to the change becoming
effective and update the "Last updated" date at the top of this Privacy Policy.

you are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
are effective when they are posted on this page.

Contact us

If you have any questions about this Privacy Policy, you can contact us:


● By visiting this page on our website: https://rpabotmonitor.com
● By sending us an email: appsupport@rpabotmonitor.com
  """;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: const Text(
            'Privacy Policy',
            style: TextStyle(color: Colors.white), // Set title color to white
          ),
          backgroundColor: customTeal,
          iconTheme: const IconThemeData(color: Colors.white)
          ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Text(
            privacyPolicyText,
            style: const TextStyle(
              fontSize: 16.0,
              color: Colors.black, // Set text color to white
            ),
            textAlign: TextAlign.justify,
          ),
        ),
      ),
    );
  }
}
