// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0nOxg2rJFx0i3-FEDrjVvxi8hMRI7gs',
    appId: '1:100329912836:web:ca931ca24b2ad74795db59',
    messagingSenderId: '100329912836',
    projectId: 'botmonitoring-notification',
    authDomain: 'botmonitoring-notification.firebaseapp.com',
    storageBucket: 'botmonitoring-notification.firebasestorage.app',
    measurementId: 'G-QNEGXC2BRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQleqRfPTjtngtO1LQUBaDoCxqxtXN8c',
    appId: '1:100329912836:android:a8b8753c588275b095db59',
    messagingSenderId: '100329912836',
    projectId: 'botmonitoring-notification',
    storageBucket: 'botmonitoring-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRJY84dhFWa00xFieLycE-xacmhNK2FE',
    appId: '1:100329912836:ios:029554cbf571fe3295db59',
    messagingSenderId: '100329912836',
    projectId: 'botmonitoring-notification',
    storageBucket: 'botmonitoring-notification.firebasestorage.app',
    iosBundleId: 'com.msl.rpa_bot_monitoring_ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRJY84dhFWa00xFieLycE-xacmhNK2FE',
    appId: '1:100329912836:ios:029554cbf571fe3295db59',
    messagingSenderId: '100329912836',
    projectId: 'botmonitoring-notification',
    storageBucket: 'botmonitoring-notification.firebasestorage.app',
    iosBundleId: 'com.msl.rpa_bot_monitoring_ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0nOxg2rJFx0i3-FEDrjVvxi8hMRI7gs',
    appId: '1:100329912836:web:0277f236f924d70e95db59',
    messagingSenderId: '100329912836',
    projectId: 'botmonitoring-notification',
    authDomain: 'botmonitoring-notification.firebaseapp.com',
    storageBucket: 'botmonitoring-notification.firebasestorage.app',
    measurementId: 'G-TPYFQD0DLB',
  );
}
